// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Xml = 0;

var Xmllexer = 0;

var Light_xml = 0;

var XmllexerE = 0;

var XmllexerI = 0;

var Xml_decode = 0;

var Xml_encode = 0;

var XmllexerI2 = 0;

var Xmllexer_generic = 0;

exports.Xml = Xml;
exports.Xmllexer = Xmllexer;
exports.Light_xml = Light_xml;
exports.XmllexerE = XmllexerE;
exports.XmllexerI = XmllexerI;
exports.Xml_decode = Xml_decode;
exports.Xml_encode = Xml_encode;
exports.XmllexerI2 = XmllexerI2;
exports.Xmllexer_generic = Xmllexer_generic;
/* No side effect */
